spring:
  application:
    name: study-notification-server

  cloud:
    function:
      definition: consumeNotification
    stream:
      bindings:
        consumeNotification-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}study.update
