spring:
  application:
    name: study-notification-server

  cloud:
    function:
      definition: "consumeNotification;consumeNotificationQuota"
    stream:
      bindings:
        consumeNotification-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}study.update
        consumeNotificationQuota-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}quota.update

powsybl-ws:
  autoconfigure:
    base-exception-handler:
      enable: false
