server:
  port: 5009

spring:
  rabbitmq:
    addresses: localhost

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: prometheus, health, info