spring:
  profiles:
    active: default,local

  application:
    name: notification-server

  rabbitmq:
    addresses: rabbitmq
    port: 5672

  cloud:
    function:
      definition: consumeNotification
    stream:
      bindings:
        consumeNotification-in-0:
          destination: study.update
